In [2]:
import pandas as pd

df = pd.read_csv("matches.csv")

# Keep only useful columns
df = df[['team1', 'team2', 'toss_winner', 'venue', 'winner']]

# Remove missing values
df = df.dropna()

print(df.head())

                         team1                        team2  \
0  Royal Challengers Bangalore        Kolkata Knight Riders
1              Kings XI Punjab          Chennai Super Kings
2             Delhi Daredevils             Rajasthan Royals
3               Mumbai Indians  Royal Challengers Bangalore
4        Kolkata Knight Riders              Deccan Chargers

                   toss_winner                                       venue  \
0  Royal Challengers Bangalore                       M Chinnaswamy Stadium
1          Chennai Super Kings  Punjab Cricket Association Stadium, Mohali
2             Rajasthan Royals                            Feroz Shah Kotla
3               Mumbai Indians                            Wankhede Stadium
4              Deccan Chargers                                Eden Gardens

                        winner
0        Kolkata Knight Riders
1          Chennai Super Kings
2             Delhi Daredevils
3  Royal Challengers Bangalore
4        Kolkata Knight Riders

In [3]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['team1'] = le.fit_transform(df['team1'])
df['team2'] = le.fit_transform(df['team2'])
df['toss_winner'] = le.fit_transform(df['toss_winner'])
df['venue'] = le.fit_transform(df['venue'])
df['winner'] = le.fit_transform(df['winner'])

In [4]:
X = df[['team1', 'team2', 'toss_winner', 'venue']]
y = df['winner']

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

print("Model trained successfully ✅")

Model trained successfully ✅

In [7]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.48623853211009177

In [8]:
model.predict([[1, 2, 1, 5]])

c:\Users\hraj1\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])

In [9]:
team_encoder = LabelEncoder()
venue_encoder = LabelEncoder()

df['team1'] = team_encoder.fit_transform(df['team1'])
df['team2'] = team_encoder.transform(df['team2'])
df['toss_winner'] = team_encoder.transform(df['toss_winner'])
df['venue'] = venue_encoder.fit_transform(df['venue'])
df['winner'] = team_encoder.transform(df['winner'])

In [10]:
from sklearn.preprocessing import LabelEncoder

team_encoder = LabelEncoder()

# Combine all team columns
all_teams = pd.concat([df['team1'], df['team2'], df['toss_winner'], df['winner']])

team_encoder.fit(all_teams)

# Transform
df['team1'] = team_encoder.transform(df['team1'])
df['team2'] = team_encoder.transform(df['team2'])
df['toss_winner'] = team_encoder.transform(df['toss_winner'])
df['winner'] = team_encoder.transform(df['winner'])

In [11]:
venue_encoder = LabelEncoder()
df['venue'] = venue_encoder.fit_transform(df['venue'])

In [12]:
df['team1'] = team_encoder.transform(df['team1'])

In [13]:
import pandas as pd

df = pd.read_csv("matches.csv")

df = df[['team1', 'team2', 'toss_winner', 'venue', 'winner']]
df = df.dropna()

In [14]:
df.head()

,team1,team2,toss_winner,venue,winner
0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,M Chinnaswamy Stadium,Kolkata Knight Riders
1,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings
2,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,Feroz Shah Kotla,Delhi Daredevils
3,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,Wankhede Stadium,Royal Challengers Bangalore
4,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,Eden Gardens,Kolkata Knight Riders

In [15]:
df.tail()

,team1,team2,toss_winner,venue,winner
1090,Punjab Kings,Sunrisers Hyderabad,Punjab Kings,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad
1091,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,"Narendra Modi Stadium, Ahmedabad",Kolkata Knight Riders
1092,Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals
1093,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad
1094,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk, Chennai",Kolkata Knight Riders

In [16]:
from sklearn.preprocessing import LabelEncoder

team_encoder = LabelEncoder()

# Combine ALL team-related columns (still TEXT)
all_teams = pd.concat([
    df['team1'],
    df['team2'],
    df['toss_winner'],
    df['winner']
])

team_encoder.fit(all_teams)

print(team_encoder.classes_)  # ✅ should show team names

['Chennai Super Kings' 'Deccan Chargers' 'Delhi Capitals'
 'Delhi Daredevils' 'Gujarat Lions' 'Gujarat Titans' 'Kings XI Punjab'
 'Kochi Tuskers Kerala' 'Kolkata Knight Riders' 'Lucknow Super Giants'
 'Mumbai Indians' 'Pune Warriors' 'Punjab Kings' 'Rajasthan Royals'
 'Rising Pune Supergiant' 'Rising Pune Supergiants'
 'Royal Challengers Bangalore' 'Royal Challengers Bengaluru'
 'Sunrisers Hyderabad']

In [17]:
df['team1'] = team_encoder.transform(df['team1'])
df['team2'] = team_encoder.transform(df['team2'])
df['toss_winner'] = team_encoder.transform(df['toss_winner'])
df['winner'] = team_encoder.transform(df['winner'])

In [18]:
venue_encoder = LabelEncoder()
df['venue'] = venue_encoder.fit_transform(df['venue'])

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X = df[['team1', 'team2', 'toss_winner', 'venue']]
y = df['winner']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train)

print("Model trained ✅")

Model trained ✅

In [20]:
team1 = "Mumbai Indians"
team2 = "Chennai Super Kings"
toss = "Mumbai Indians"
venue = "Wankhede Stadium"

input_data = [[
    team_encoder.transform([team1])[0],
    team_encoder.transform([team2])[0],
    team_encoder.transform([toss])[0],
    venue_encoder.transform([venue])[0]
]]

prediction = model.predict(input_data)
print("Predicted winner:", team_encoder.inverse_transform(prediction))

Predicted winner: ['Mumbai Indians']

c:\Users\hraj1\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [21]:
probs = model.predict_proba(input_data)

print(probs)

[[0.24658333 0.         0.         0.         0.         0.
  0.         0.         0.01       0.         0.74341667 0.
  0.         0.         0.         0.         0.         0.
  0.        ]]

c:\Users\hraj1\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [22]:
classes = model.classes_

for i, prob in enumerate(probs[0]):
    team_name = team_encoder.inverse_transform([classes[i]])[0]
    print(f"{team_name} → {round(prob*100, 2)}%")

Chennai Super Kings → 24.66%
Deccan Chargers → 0.0%
Delhi Capitals → 0.0%
Delhi Daredevils → 0.0%
Gujarat Lions → 0.0%
Gujarat Titans → 0.0%
Kings XI Punjab → 0.0%
Kochi Tuskers Kerala → 0.0%
Kolkata Knight Riders → 1.0%
Lucknow Super Giants → 0.0%
Mumbai Indians → 74.34%
Pune Warriors → 0.0%
Punjab Kings → 0.0%
Rajasthan Royals → 0.0%
Rising Pune Supergiant → 0.0%
Rising Pune Supergiants → 0.0%
Royal Challengers Bangalore → 0.0%
Royal Challengers Bengaluru → 0.0%
Sunrisers Hyderabad → 0.0%

In [23]:
team1 = "Mumbai Indians"
team2 = "Chennai Super Kings"

for i, prob in enumerate(probs[0]):
    team_name = team_encoder.inverse_transform([classes[i]])[0]
    
    if team_name == team1 or team_name == team2:
        print(f"{team_name} → {round(prob*100, 2)}%")

Chennai Super Kings → 24.66%
Mumbai Indians → 74.34%

In [24]:
winner = model.predict(input_data)
print("Predicted Winner:", team_encoder.inverse_transform(winner)[0])

Predicted Winner: Mumbai Indians

c:\Users\hraj1\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [25]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))

In [26]:
import pickle

pickle.dump(team_encoder, open("team_encoder.pkl", "wb"))
pickle.dump(venue_encoder, open("venue_encoder.pkl", "wb"))

In [27]:
# Calculate win rate
win_counts = df['winner'].value_counts()

df['team1_win_rate'] = df['team1'].map(win_counts) / len(df)
df['team2_win_rate'] = df['team2'].map(win_counts) / len(df)

In [28]:
def head_to_head(row):
    matches = df[(df['team1'] == row['team1']) & (df['team2'] == row['team2'])]
    return len(matches)

df['h2h'] = df.apply(head_to_head, axis=1)

In [29]:
X = df[['team1', 'team2', 'toss_winner', 'venue', 'team1_win_rate', 'team2_win_rate']]